---
title: "Example"
author: "Tanmay"
bibliography: "bibliography.bib"
date: \today
link-citations: true
urlcolor: "blue"
linkReferences: true
figPrefix:
    - "Figure."
    - "Figures."
eqnPrefix:
    - "Eqn."
    - "Eqns."
tblPrefix:
    - "Table."
    - "Tables."
---